#!/usr/bin/env python
import sys, json

print "Reading input parameters from 'input.json' file"
with open(sys.argv[1]) as data_file:
  data = json.load(data_file)
  num_of_samples = data["num_of_samples"]

print "Number of samples - ", num_of_samples

print "Writing input parameters to 'input.txt' file"
with open("input.txt", "w") as f:
  f.write(str(num_of_samples))
