#!/usr/bin/env python
import sys, json

with open(sys.argv[1]) as data_file:    
  data = json.load(data_file)
  num_of_samples = data["num_of_samples"]

with open("input.txt", "w") as f:
  f.write(str(num_of_samples))


